### ISSUE TITLE
Distribution of xsdvi.jar should be in Releases, not inside Git repo

### ISSUE THREAD

**Issue by ronaldtse** [Intelligent2013/xsdvi#1]
Distribution of xsdvi.jar should be in Releases, not inside Git repo

**Comment by Intelligent2013** [comment]
@ronaldtse done: https://github.com/metanorma/xsdvi/releases/download/v1.0/xsdvi-1.0.jar

**Comment by ronaldtse** [comment]
Thanks @Intelligent2013 !
