### ISSUE TITLE
Annotation/Documentatin not shown in the SVG

### ISSUE THREAD

**Issue by oliverunger** [Intelligent2013/xsdvi#5]
For example:
![image](https://github.com/metanorma/xsdvi/assets/97088274/387b8441-7272-4f2b-9fa5-26b3c12f05b9)

Is it possible to enable this?

**Comment by ronaldtse** [comment]
@oliverunger thank you for the report. Are we not displaying the `<xsd:documentation>` content?

@Intelligent2013 could you have a look at this?

**Comment by oliverunger** [comment]
Thank you for your fast response. I generated the example UnitsML-v1.0-csd04.svg and I cant see any docs:
![image](https://github.com/metanorma/xsdvi/assets/97088274/aa3a7b51-bea0-47d1-b523-f2efe46825e4)

This is how it looks in XMLSpy
![image](https://github.com/metanorma/xsdvi/assets/97088274/1734a6cd-ac88-40bf-aba0-c517b1c52a7f)

**Comment by Intelligent2013** [comment]
`metanorma/xsdvi` is a fork of the original `XsdVi` source code (https://sourceforge.net/projects/xsdvi/) that doesn't support the the `xsd:documentation` rendering. 
In the Metanorma we're using XsdVi  as part of https://github.com/metanorma/xsd-doc-tools. We're using [xs3p](https://github.com/metanorma/xs3p) tool for generating documentation.

I need some time for adding the new feature in the `XsdVi`. I see two possibilities:
- add tooltip with the documentation text (I think it doesn't take a lot of time)
- add documentation block below the element diagram (maybe this requires the full code refactoring)

**Comment by ronaldtse** [comment]
@Intelligent2013 If the user can use xs3p, what's the best way to allow the user to generate documentation?

I think the issue from @oliverunger is that the UnitsML schemas don't provide adequate documentation in the generated HTML.

**Comment by Intelligent2013** [comment]
> @Intelligent2013 If the user can use xs3p, what's the best way to allow the user to generate documentation?
> 

@ronaldtse the documentation can be generated in two steps. From the example https://github.com/metanorma/xsd-doc-tools/blob/master/Makefile:

1. to generate SVG diagrams for each XSD element:
```
	java -jar $(XSDVIPATH) $(CURDIR)/$< \
		-rootNodeName all \
		-oneNodeOnly \
		-outputPath $(dir $@)diagrams; \
```

2. to generate HTML documentation with integrated SVG from step 1:
```
	xsltproc --nonet \
		--param title "'Schema documentation $(notdir $*)'" \
		--output $@ $(XS3PPATH) $<
```

The resulted HTML fragment for the element `UnitSet` looks so:
![image](https://github.com/metanorma/xsdvi/assets/5559926/bec7432d-d29b-4217-b33a-8a8049e9ae76)

Note: SVG diagram (generated by `XsdVi`) doesn't contain the documentation. The documentation renders as part of the HTML (generated by `xs3p`).

> I think the issue from @oliverunger is that the UnitsML schemas don't provide adequate documentation in the generated HTML.

@oliverunger mentioned that _SVG diagram_ doesn't contain the documentation. As I understood, he would like to generate the standalone SVG with the integrated documentation (as XMLSpy do it), without HTML shell.

**Comment by oliverunger** [comment]
@Intelligent2013 
Thats correct. The text in the documentation is not shown

**Comment by ronaldtse** [comment]
Thanks for reminding me of the focus. It would be much better if we can insert the documentation into the diagram without needing it to be a tooltip, like XMLSpy.

However as @Intelligent2013 said, heavy refactoring / recoding will be necessary because this works involves changing the resulting SVG.

We *could* potentially embark in a journey to do that, but the key is to separate SVG rendering from the XSD modeling? What do you think?

**Comment by Intelligent2013** [comment]
Currently (https://github.com/metanorma/xsdvi/pull/6), the description renders for the elements:
![image](https://github.com/metanorma/xsdvi/assets/5559926/821aa97c-9f41-4d87-aa2e-422cc5eb171b)

Example: 
[UnitsML-v1.0-csd04.zip](https://github.com/metanorma/xsdvi/files/12590134/UnitsML-v1.0-csd04.zip)


Next, I'll add support for the attributes.
XSD allows the annotations for _all_ element, so may be I need more time to support them.

**Comment by oliverunger** [comment]
@Intelligent2013 Cool that you are making progress 👍

**Comment by Intelligent2013** [comment]
Done in https://github.com/metanorma/xsdvi/releases/tag/v1.1.

![image](https://github.com/metanorma/xsdvi/assets/5559926/3e4931f2-9a3f-40fe-b736-cccfa6423c99)
